"""creating table

Revision ID: 1181fb66244d
Revises: f70f08f0ab53
Create Date: 2023-09-22 12:56:47.251977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1181fb66244d'
down_revision = 'f70f08f0ab53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_product_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_product_id_products'), 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_product_id_products'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_product_id_users', 'users', ['product_id'], ['id'])

    # ### end Alembic commands ###
