"""creating table

Revision ID: 659d53979f2e
Revises: 4af1a0aacdb5
Create Date: 2023-09-22 13:23:36.580695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659d53979f2e'
down_revision = '4af1a0aacdb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
