"""table changes

Revision ID: ba73a9ccb84a
Revises: 659d53979f2e
Create Date: 2023-10-04 13:43:39.743653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba73a9ccb84a'
down_revision = '659d53979f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('product_image')
        batch_op.drop_column('product_price')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_orders_product_id_products'), 'products', ['product_id'], ['id'])
        batch_op.drop_column('product_price')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('product_price', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_orders_product_id_products'), type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('product_price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('product_image', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
