"""creating table

Revision ID: f70f08f0ab53
Revises: 90e53bd42b0c
Create Date: 2023-09-22 12:55:08.152557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70f08f0ab53'
down_revision = '90e53bd42b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_reviews_product_id_users'), 'users', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_product_id_users'), type_='foreignkey')

    # ### end Alembic commands ###
